// <auto-generated />
using System;
using EstacionamentoAPI.Data;
using EstacionamentoAPI.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EstacionamentoAPI.Migrations
{
    [DbContext(typeof(EstacionamentoContext))]
    partial class EstacionamentoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status_pagamento_enum", new[] { "cancelado", "concluido", "pago", "pendente" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EstacionamentoAPI.Models.Acesso", b =>
                {
                    b.Property<int>("IdAcesso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_acesso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAcesso"));

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("timestamp")
                        .HasColumnName("hora_entrada");

                    b.Property<DateTime?>("HoraSaida")
                        .HasColumnType("timestamp")
                        .HasColumnName("hora_saida");

                    b.Property<int>("IdTarifa")
                        .HasColumnType("integer")
                        .HasColumnName("id_tarifa");

                    b.Property<int>("IdVaga")
                        .HasColumnType("integer")
                        .HasColumnName("id_vaga");

                    b.Property<int>("IdVeiculo")
                        .HasColumnType("integer")
                        .HasColumnName("id_veiculo");

                    b.Property<TimeSpan?>("TempoPermanencia")
                        .HasColumnType("interval")
                        .HasColumnName("tempo_permanencia");

                    b.Property<string>("Ticket")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket");

                    b.HasKey("IdAcesso")
                        .HasName("pk_acesso_veiculo");

                    b.HasIndex("IdTarifa")
                        .HasDatabaseName("ix_acesso_veiculo_id_tarifa");

                    b.HasIndex("IdVaga")
                        .HasDatabaseName("ix_acesso_veiculo_id_vaga");

                    b.HasIndex("IdVeiculo")
                        .HasDatabaseName("ix_acesso_veiculo_id_veiculo");

                    b.HasIndex("Ticket")
                        .IsUnique()
                        .HasDatabaseName("ix_acesso_veiculo_ticket");

                    b.ToTable("acesso_veiculo", null, t =>
                        {
                            t.HasCheckConstraint("CK_HoraSaida_Maior_Entrada", "hora_saida IS NULL OR hora_saida >= hora_entrada");
                        });
                });

            modelBuilder.Entity("EstacionamentoAPI.Models.Aviso", b =>
                {
                    b.Property<int>("IdAviso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_aviso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAviso"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("IdAviso")
                        .HasName("pk_aviso");

                    b.ToTable("aviso", (string)null);
                });

            modelBuilder.Entity("EstacionamentoAPI.Models.Feedback", b =>
                {
                    b.Property<int>("IdFeedback")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_feedback");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFeedback"));

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp")
                        .HasColumnName("data_envio");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensagem");

                    b.HasKey("IdFeedback")
                        .HasName("pk_feedback");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_feedback_id_usuario");

                    b.ToTable("feedback", (string)null);
                });

            modelBuilder.Entity("EstacionamentoAPI.Models.Ocorrencia", b =>
                {
                    b.Property<int>("IdOcorrencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_ocorrencia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOcorrencia"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp")
                        .HasColumnName("data_hora");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("IdAcesso")
                        .HasColumnType("integer")
                        .HasColumnName("id_acesso");

                    b.HasKey("IdOcorrencia")
                        .HasName("pk_ocorrencia");

                    b.HasIndex("IdAcesso")
                        .HasDatabaseName("ix_ocorrencia_id_acesso");

                    b.ToTable("ocorrencia", (string)null);
                });

            modelBuilder.Entity("EstacionamentoAPI.Models.Pagamento", b =>
                {
                    b.Property<int>("IdPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pagamento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPagamento"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp")
                        .HasColumnName("data_hora");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("forma_pagamento");

                    b.Property<int>("IdAcesso")
                        .HasColumnType("integer")
                        .HasColumnName("id_acesso");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<StatusPagamentoEnum>("StatusPagamento")
                        .HasColumnType("status_pagamento_enum")
                        .HasColumnName("status_pagamento");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_pago");

                    b.HasKey("IdPagamento")
                        .HasName("pk_pagamento");

                    b.HasIndex("IdAcesso")
                        .IsUnique()
                        .HasDatabaseName("ix_pagamento_id_acesso");

                    b.ToTable("pagamento", (string)null);
                });

            modelBuilder.Entity("EstacionamentoAPI.Models.Tarifa", b =>
                {
                    b.Property<int>("IdTarifa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tarifa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTarifa"));

                    b.Property<decimal>("DescontoFuncionario")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("desconto_funcionario");

                    b.Property<decimal>("DescontoParceiro")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("desconto_parceiro");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("TipoTarifa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_tarifa");

                    b.Property<decimal>("ValorDiaria")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_diaria");

                    b.Property<decimal>("ValorHoraAdicional")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_hora_adicional");

                    b.Property<decimal>("ValorPrimeiraHora")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_primeira_hora");

                    b.HasKey("IdTarifa")
                        .HasName("pk_tarifa");

                    b.ToTable("tarifa", (string)null);

                    b.HasData(
                        new
                        {
                            IdTarifa = 1,
                            DescontoFuncionario = 0.00m,
                            DescontoParceiro = 0.00m,
                            RowVersion = 0u,
                            TipoTarifa = "Padrao",
                            ValorDiaria = 50.00m,
                            ValorHoraAdicional = 5.00m,
                            ValorPrimeiraHora = 10.00m
                        });
                });

            modelBuilder.Entity("EstacionamentoAPI.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cargo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SenhaAcesso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_acesso");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("telefone");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_usuario");

                    b.HasKey("IdUsuario")
                        .HasName("pk_usuario");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_cpf");

                    b.ToTable("usuario", null, t =>
                        {
                            t.HasCheckConstraint("CK_Usuario_Cpf", "cpf ~ '^[0-9]{11}$'");

                            t.HasCheckConstraint("CK_Usuario_DataNascimento", "data_nascimento <= CURRENT_DATE");
                        });
                });

            modelBuilder.Entity("EstacionamentoAPI.Models.Vaga", b =>
                {
                    b.Property<int>("IdVaga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_vaga");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVaga"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status");

                    b.Property<string>("TipoVaga")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("tipo_vaga");

                    b.HasKey("IdVaga")
                        .HasName("pk_vaga");

                    b.ToTable("vaga", (string)null);

                    b.HasData(
                        new
                        {
                            IdVaga = 1,
                            Status = "Disponivel",
                            TipoVaga = "Carro"
                        },
                        new
                        {
                            IdVaga = 2,
                            Status = "Disponivel",
                            TipoVaga = "Carro"
                        },
                        new
                        {
                            IdVaga = 3,
                            Status = "Disponivel",
                            TipoVaga = "Moto"
                        },
                        new
                        {
                            IdVaga = 4,
                            Status = "Disponivel",
                            TipoVaga = "Moto"
                        },
                        new
                        {
                            IdVaga = 5,
                            Status = "Disponivel",
                            TipoVaga = "Caminhonete"
                        },
                        new
                        {
                            IdVaga = 6,
                            Status = "Disponivel",
                            TipoVaga = "Caminhonete"
                        },
                        new
                        {
                            IdVaga = 7,
                            Status = "Disponivel",
                            TipoVaga = "Caminhao"
                        },
                        new
                        {
                            IdVaga = 8,
                            Status = "Disponivel",
                            TipoVaga = "Caminhao"
                        });
                });

            modelBuilder.Entity("EstacionamentoAPI.Models.Veiculo", b =>
                {
                    b.Property<int>("IdVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_veiculo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVeiculo"));

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("char(7)")
                        .HasColumnName("placa");

                    b.Property<string>("TipoVeiculo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_veiculo");

                    b.HasKey("IdVeiculo")
                        .HasName("pk_veiculo");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_veiculo_id_usuario");

                    b.HasIndex("Placa")
                        .IsUnique()
                        .HasDatabaseName("ix_veiculo_placa");

                    b.ToTable("veiculo", null, t =>
                        {
                            t.HasCheckConstraint("CK_Veiculo_Placa", "placa ~ '^[A-Za-z0-9]{7}$'");
                        });
                });

            modelBuilder.Entity("EstacionamentoAPI.Models.Acesso", b =>
                {
                    b.HasOne("EstacionamentoAPI.Models.Tarifa", "Tarifa")
                        .WithMany()
                        .HasForeignKey("IdTarifa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_acesso_veiculo_tarifa_id_tarifa");

                    b.HasOne("EstacionamentoAPI.Models.Vaga", "Vaga")
                        .WithMany()
                        .HasForeignKey("IdVaga")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_acesso_veiculo_vaga_id_vaga");

                    b.HasOne("EstacionamentoAPI.Models.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("IdVeiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_acesso_veiculo_veiculo_id_veiculo");

                    b.Navigation("Tarifa");

                    b.Navigation("Vaga");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("EstacionamentoAPI.Models.Feedback", b =>
                {
                    b.HasOne("EstacionamentoAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_usuario_id_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EstacionamentoAPI.Models.Ocorrencia", b =>
                {
                    b.HasOne("EstacionamentoAPI.Models.Acesso", "Acesso")
                        .WithMany()
                        .HasForeignKey("IdAcesso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ocorrencia_acesso_veiculo_id_acesso");

                    b.Navigation("Acesso");
                });

            modelBuilder.Entity("EstacionamentoAPI.Models.Pagamento", b =>
                {
                    b.HasOne("EstacionamentoAPI.Models.Acesso", "Acesso")
                        .WithOne("Pagamento")
                        .HasForeignKey("EstacionamentoAPI.Models.Pagamento", "IdAcesso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pagamento_acesso_veiculo_id_acesso");

                    b.Navigation("Acesso");
                });

            modelBuilder.Entity("EstacionamentoAPI.Models.Veiculo", b =>
                {
                    b.HasOne("EstacionamentoAPI.Models.Usuario", "Usuario")
                        .WithMany("Veiculos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_veiculo_usuario_id_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EstacionamentoAPI.Models.Acesso", b =>
                {
                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("EstacionamentoAPI.Models.Usuario", b =>
                {
                    b.Navigation("Veiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
